# Generated by Django 3.2.2 on 2021-05-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210517_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
