# Generated by Django 3.2.2 on 2021-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
